services:
  windows:
    image: dockurr/windows
    container_name: windows
    env_file:
      - .env
    devices:
      - /dev/kvm
      - /dev/net/tun
      - /dev/bus/usb:/dev/bus/usb
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
      - 2222:22/tcp
    volumes:
      - /var/win:/storage
      - /home/fabricio/shared:/data
      - ./install:/oem
    restart: always
    stop_grace_period: 2m
